version: '3' 
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports: 
      - '5432:5432'

  web: 
    build:
      context: .
    command: bash -c 'flask set-database && flask run -p 5000 -h 0.0.0.0'
    ports: 
      - '5000:5000'
    environment:
      SQLALCHEMY_DATABASE_URI: 'postgresql://postgres:example@db/example'
      REDIS_URL: 'redis://redis:6379/0'
    restart: always
    depends_on:
      - redis
      - db

  worker:
    build: 
      context: .
    command: 'rq worker -u redis://redis:6379/0 background-task --with-scheduler'
    environment:
      REDIS_URL: redis://redis:6379/0
    restart: always
    depends_on:
      - db
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080